name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Authenticate to Salesforce
        run: |
            echo "${{ secrets.SF_AUTH_URL }}" > authURL.txt
            sfdx force:auth:sfdxurl:store -f ./authURL.txt -a carCRM --setdefaultusername

      - name: Verify org connection
        run: sfdx force:org:display -u carCRM

      - name: Deploy source to Salesforce
        run: |
          sfdx force:source:deploy -p force-app --json --loglevel fatal
